# Generated by Django 4.2.2 on 2023-07-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('paragraph1', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph3', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(max_length=100)),
                ('paragraph4', models.CharField(blank=True, max_length=100, null=True)),
                ('title3', models.CharField(max_length=100)),
                ('paragraph5', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
