# Generated by Django 4.2.2 on 2023-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuai', '0002_aggrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aggrement',
            name='paragraph6',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
