# Generated by Django 4.2.2 on 2023-06-11 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_details',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
