# Generated by Django 4.2.2 on 2023-06-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_contact_details_createdat_contact_details_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
