# Generated by Django 4.2.2 on 2023-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_sales_infor_payment_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('customers_enrolled', models.CharField(max_length=15)),
                ('percentage', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
