# Generated by Django 4.2.2 on 2023-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_offerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(max_length=30)),
                ('description1', models.TextField(max_length=500)),
                ('service2', models.CharField(max_length=30)),
                ('description2', models.TextField(max_length=500)),
                ('service3', models.CharField(max_length=30)),
                ('description3', models.TextField(max_length=500)),
                ('service4', models.CharField(max_length=30)),
                ('description4', models.TextField(max_length=500)),
                ('service5', models.CharField(max_length=30)),
                ('description5', models.TextField(max_length=500)),
                ('service6', models.CharField(max_length=30)),
                ('description6', models.TextField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='promotion',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
