# Generated by Django 4.2.2 on 2023-06-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0009_service_icon_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='customers_enrolled',
            new_name='customersEnrolled',
        ),
    ]
