# Generated by Django 4.2.2 on 2023-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_rename_customers_enrolled_promotion_customersenrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='customersEnrolled',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='infor',
            name='percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='infor',
            name='promotion_message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
